stock_list:
  - RELIANCE
  - HDFCBANK
  - ICICIBANK
  - INFY
  - TCS
  - ITC
  - KOTAKBANK
  - HINDUNILVR
  - SBIN
  - LT
  - AXISBANK
  - BHARTIARTL
  - HCLTECH
  - ASIANPAINT
  - MARUTI
  - BAJFINANCE
  - HDFCLIFE
  - ULTRACEMCO
  - BAJAJFINSV
  - WIPRO
  - POWERGRID
  - NTPC
  - NESTLEIND
  - SUNPHARMA
  - TECHM
  - TITAN
  - ADANIENT
  - ADANIPORTS
  - COALINDIA
  - TATAMOTORS
  - JSWSTEEL
  - GRASIM
  - ONGC
  - HINDALCO
  - SBILIFE
  - DRREDDY
  - BPCL
  - IOC
  - DIVISLAB
  - BRITANNIA
  - CIPLA
  - SHREECEM
  - BAJAJ-AUTO
  - HEROMOTOCO
  - EICHERMOT
  - INDUSINDBK
  - HAVELLS
  - DABUR
  - GODREJCP
  - M&M
  - TATACONSUM
  - PIDILITIND
  - UPL
  - GAIL
  - SIEMENS
  - BOSCHLTD
  - AMBUJACEM
  - ACC
  - BANDHANBNK
  - BIOCON
  - LTI
  - MUTHOOTFIN
  - PAGEIND
  - PETRONET
  - PEL
  - PNB
  - SAIL
  - SRF
  - TATAPOWER
  - TRENT
  - TVSMOTOR
  - VEDL
  - ZEEL
  - ADANIGREEN
  - ADANITRANS
  - AUBANK
  - BANKBARODA
  - BERGEPAINT
  - CANBK
  - CHOLAFIN
  - DELTACORP
  - ESCORTS
  - FEDERALBNK
  - GICRE
  - ICICIGI
  - ICICIPRULI
  - IDFCFIRSTB
  - IEX
  - INDIGO
  - INDUSTOWER
  - IRCTC
  - LODHA
  - MRF
  - NAUKRI
  - PIIND
  - PVR
  - RECLTD
  - RBLBANK
  - SUNDARMFIN
  - TATACHEM
  - TATAELXSI
  - TORNTPOWER
  - ZYDUSLIFE
index_symbol: "NIFTY"
top_n: 50