stock_list:
  - RELIANCE
  - TCS
  - INFY
  - HDFCBANK
  - ICICIBANK
  - LT
  - KOTAKBANK
  - SBIN
  - AXISBANK
  - BHARTIARTL
  - ITC
  - HINDUNILVR
  - ASIANPAINT
  - MARUTI
  - SUNPHARMA
  - TITAN
  - HCLTECH
  - WIPRO
  - NTPC
  - POWERGRID
  - ULTRACEMCO
  - HINDALCO
  - JSWSTEEL
  - TATASTEEL
  - BAJFINANCE
  - BAJAJFINSV
  - NESTLEIND
  - BRITANNIA
  - DIVISLAB
  - TECHM
  - EICHERMOT
  - HEROMOTOCO
  - GRASIM
  - UPL
  - DRREDDY
  - COALINDIA
  - CIPLA
  - SBILIFE
  - HDFCLIFE
  - BAJAJ-AUTO
  - M&M
  - ADANIENT
  - ADANIPORTS
  - TATACONSUM
  - INDUSINDBK
  - BPCL
  - ONGC
  - APOLLOHOSP
  - TATAMOTORS
  - HDFCAMC
index_symbol: "NIFTY"
top_n: 50
