kite_access_token: tyZc0su5rAZZ4eN7P0iZ1gNyVmtdgB4Y
kite_api_key: kut7ix3qpu48c2m1
kite_api_secret: gzjcxjm6di8txttk0f7p69g8f9zjj0zk

telegram_bot_token: 7159845565:AAHnwEzka4W4DJqTZyCCU7zsc981Gopq_HQ
telegram_chat_id:
- "5876050645"
- "7381430287"
