RELIANCE: NIFTYENERGY
HDFCBANK: NIFTYBANK
ICICIBANK: NIFTYBANK
INFY: NIFTYIT
TCS: NIFTYIT
ITC: NIFTYFMCG
KOTAKBANK: NIFTYBANK
HINDUNILVR: NIFTYFMCG
SBIN: NIFTYBANK
LT: NIFTYINFRA
AXISBANK: NIFTYBANK
BHARTIARTL: NIFTYMEDIA
HCLTECH: NIFTYIT
ASIANPAINT: NIFTYFMCG
MARUTI: NIFTYAUTO
BAJFINANCE: NIFTYFIN
HDFCLIFE: NIFTYFIN
ULTRACEMCO: NIFTYINFRA
BAJAJFINSV: NIFTYFIN
WIPRO: NIFTYIT
POWERGRID: NIFTYINFRA
NTPC: NIFTYENERGY
NESTLEIND: NIFTYFMCG
SUNPHARMA: NIFTYPHARMA
TECHM: NIFTYIT
TITAN: NIFTYFMCG
ADANIENT: NIFTYCOMMODITIES
ADANIPORTS: NIFTYINFRA
COALINDIA: NIFTYENERGY
TATAMOTORS: NIFTYAUTO
JSWSTEEL: NIFTYMETAL
GRASIM: NIFTYINFRA
ONGC: NIFTYENERGY
HINDALCO: NIFTYMETAL
SBILIFE: NIFTYFIN
DRREDDY: NIFTYPHARMA
BPCL: NIFTYENERGY
IOC: NIFTYENERGY
DIVISLAB: NIFTYPHARMA
BRITANNIA: NIFTYFMCG
CIPLA: NIFTYPHARMA
SHREECEM: NIFTYINFRA
BAJAJ-AUTO: NIFTYAUTO
HEROMOTOCO: NIFTYAUTO
EICHERMOT: NIFTYAUTO
INDUSINDBK: NIFTYBANK
HAVELLS: NIFTYINFRA
DABUR: NIFTYFMCG
GODREJCP: NIFTYFMCG
M&M: NIFTYAUTO
TATACONSUM: NIFTYFMCG
PIDILITIND: NIFTYFMCG
UPL: NIFTYCHEMICAL
GAIL: NIFTYENERGY
SIEMENS: NIFTYINFRA
BOSCHLTD: NIFTYAUTO
AMBUJACEM: NIFTYINFRA
ACC: NIFTYINFRA
BANDHANBNK: NIFTYBANK
BIOCON: NIFTYPHARMA
LTI: NIFTYIT
MUTHOOTFIN: NIFTYFIN
PAGEIND: NIFTYFMCG
PETRONET: NIFTYENERGY
PEL: NIFTYFIN
PNB: NIFTYBANK
SAIL: NIFTYMETAL
SRF: NIFTYCHEMICAL
TATAPOWER: NIFTYENERGY
TRENT: NIFTYFMCG
TVSMOTOR: NIFTYAUTO
VEDL: NIFTYMETAL
ZEEL: NIFTYMEDIA
ADANIGREEN: NIFTYENERGY
ADANITRANS: NIFTYINFRA
AUBANK: NIFTYBANK
BANKBARODA: NIFTYBANK
BERGEPAINT: NIFTYFMCG
CANBK: NIFTYBANK
CHOLAFIN: NIFTYFIN
DELTACORP: NIFTYSERVICES
ESCORTS: NIFTYAUTO
FEDERALBNK: NIFTYBANK
GICRE: NIFTYFIN
ICICIGI: NIFTYFIN
ICICIPRULI: NIFTYFIN
IDFCFIRSTB: NIFTYBANK
IEX: NIFTYINFRA
INDIGO: NIFTYSERVICES
INDUSTOWER: NIFTYINFRA
IRCTC: NIFTYSERVICES
LODHA: NIFTYINFRA
MRF: NIFTYAUTO
NAUKRI: NIFTYSERVICES
PIIND: NIFTYCHEMICAL
PVR: NIFTYMEDIA
RECLTD: NIFTYFIN
RBLBANK: NIFTYBANK
SUNDARMFIN: NIFTYFIN
TATACHEM: NIFTYCHEMICAL
TATAELXSI: NIFTYIT
TORNTPOWER: NIFTYENERGY
ZYDUSLIFE: NIFTYPHARMA
